### ISSUE TITLE
NVRAppDevOps PowerShell Modules

### ISSUE THREAD

**Issue by andreasblueher** [kine/MSDYN365BC_Yaml#1]
Hello Kamil, 

Thanks for your investment into BC automated builds and deployment. I'm very interested to read more about your findings, since we're on the same path although a little bit behind ;-).

You're using NVRAppDevOps commandlets throughout your templates. I've not been able to find any sources for this module and I was wondering if you're planning to release those information? If so, will you release more information on how your AL Configuration does look like asf.

Cheers,
Andreas

**Comment by kine** [comment]
Hi Andreas,
the PS module is live on https://www.powershellgallery.com/packages/NVRAppDevOps. I am not decided if the source code will be available on GitHub or not. You have still access to the scripts when you install the module anyway.

The AL Configuration mostly includes data from app.json and from the Settings.ps1 from the template you can find here: https://github.com/kine/MSDyn365BC_AppTemplate

**Comment by kine** [comment]
Ok, the module is available here: https://github.com/kine/NVRAppDevOps
