### ISSUE TITLE
Build pipeline fails:  

### ISSUE THREAD

**Issue by epernst** [kine/MSDYN365BC_Yaml#6]
When I'm trying to build then I'm getting this error:
Repository MSDYN365BC_Yaml references endpoint GitHub which does not exist or is not authorized for use,
Unexpected step type: 'StepsTemplateReference'

**Comment by kine** [comment]
There is security thing in AzureDevOps. First time using the remote endpoint, you need to go to the build and save it somehow in the AzureDevOps designer. it will authorize the endpoint to be used. Try to edit the pipeline in any way on the Azure DevOps portal.

**Comment by epernst** [comment]
Yes I tried to add GitHub to the list of service providers in DevOps, but that didn't change it.

**Comment by kine** [comment]
No, this is not enough. See this: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=vsts#troubleshooting-authorization-for-a-yaml-pipeline

**Comment by epernst** [comment]
I don't know exactly what was wrong, but somehow I couldn't get it work with the Default agent, had to create a new AgentPool with a new name for it to run.

Now I'm getting a bit further:

2019-01-23T14:49:16.6081304Z Creating Windows user epernst
2019-01-23T14:49:17.7795437Z ##[error]docker : Sqlcmd: Error: Syntax error at line 1 near command '.'.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.4.3.2\ContainerHandling\Wait-NavContainerReady.ps1:3

3 char:21

+             $logs = docker logs $containerName

+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (Sqlcmd: Error: ...ar command '.'.:String) [], RemoteException

    + FullyQualifiedErrorId : NativeCommandError
2019-01-23T14:49:17.7848938Z Setting SA Password and enabling SA
2019-01-23T14:49:17.7922863Z ##[error]PowerShell exited with code '1'.
2019-01-23T14:49:17.8335977Z ##[section]Finishing: Prepare environment

It looks like an error in NavContainerHelper, so something in that direction. But did you see this error before?

**Comment by kine** [comment]
Please, open new issue for this. I will close this original one which was about the endpoint authentication. Thanks for understanding.

**Comment by epernst** [comment]
It was a wrong user password....

**Comment by epernst** [comment]
That tip did not work. But I removed the service provider and added it again. Then it worked.
